spring.application.name=drools-poc-local
#debug=true

server.port=8080

#H2 in-memory DB (swap for real DB in prod)
spring.datasource.url=jdbc:h2:mem:droolsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 console at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#  JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#  Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#  Logging
#logging.level.com.poc.drools=DEBUG
logging.level.org.flywaydb=INFO

# Enable trace logging for Drools core packages
logging.level.org.drools=TRACE
logging.level.org.kie=TRACE
logging.level.org.kie.api=TRACE
logging.level.org.kie.internal=TRACE

# Property to deal with empty or null values in json
spring.jackson.deserialization.fail-on-null-for-primitives=false


